### ISSUE TITLE
Lots of junk entries in the Flamingo address book

### ISSUE THREAD

**Issue by ralphlange** [epics-base/website#11]
While the junk users that appeared in the "open" registration period have been removed, the "Flamingo" address book still has >100 entries.

**Comment by ttkorhonen** [comment]
We can of course remove them. However, I left them in intentinally at this stage. One reason was to keep some record of what had happened with the registrations, somebody might have had a legitimate reason to register, etc. And, as far as I understand, the address book entries are harmless, the people cannot log in or do anything on the site.

**Comment by keijokorhonen** [comment]
Whoops! I just managed to clean the address book, as most entries were either spam or tests. The messages that we received have been marked as spam, but are still visible if necessary (none of them are really interesting to us however).
