### ISSUE TITLE
Embedded images on How-To pages point to APS Wiki site

### ISSUE THREAD

**Issue by ralphlange** [epics-base/website#12]
I found that embedded images are still hot-linked to their original location on the APS Wiki pages.

What's the suggested procedure to move the images to the new site?

**Comment by keijokorhonen** [comment]
I have found 3 embedded images on the "How to Set Up NAL (Nagios Alarm Handler) to monitor an EPICS network". If this is the only page with embedded images, it would be easy to just reupload the content to the new site.

**Comment by ralphlange** [comment]
OK, that's true.
I asked the original contributors of that page (which also has a set of dead links) to join the group of contributors of the new web site and start by updating their NAL How-To.
Question answered - closing the issue.
