### ISSUE TITLE
Flag banner (keyVisual USER) uses wrong Chinese flag

### ISSUE THREAD

**Issue by ralphlange** [epics-base/website#14]
Reported by 阎映炳 &lt;yanyingbing _AT_ sinap.ac.cn&gt;:

By the way, the **incorrect figure of national flag of China** (the second one from the right side) is used in the projects page (https://epics-controls.org/epics-users/projects/). Five yellow stars should be in the top left part. Please use the correct one (see the attachment) to replace it. Thank you very much.

![flag_of_china](https://user-images.githubusercontent.com/632191/45256205-7045ff00-b393-11e8-9fdd-78849dfee339.png)

**Comment by ralphlange** [comment]
@anjohnson - you might want to take note of this for the old site.

**Comment by anjohnson** [comment]
The only page with flags on the old website is the [sites page](https://epics.anl.gov/sites.php), which has the correct flag for China in the fifth position from the left. The flag that is fifth from the right and looks a little bit like it is the Turkish flag.

**Comment by ralphlange** [comment]
OK, so the issue with the USER key visual is that the stars in the Chinese flag should be smaller and in the top left corner instead of large and in the middle. Fair enough.

**Comment by ralphlange** [comment]
@epicDirk provided a new banner for the USERS page. Thanks!

However - sorry! - I realized we also need one labelled PROJECTS for the projects page (where Yan Yingbing found the flag to be wrong).

**Comment by epicDirk** [comment]
besides adding Pakistan i will ad PROJECTS to the banner

**Comment by epicDirk** [comment]
Today i learned that there are [EPICS user in iran](https://www.researchgate.net/publication/286073095_Iranian_Light_Source_Facility_A_third_generation_light_source_laboratory).

[And also in Portugal.](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=6&ved=2ahUKEwjfu-OKvuDfAhVRbFAKHWtUCtwQFjAFegQIBhAC&url=https%3A%2F%2Feg.uc.pt%2Fbitstream%2F10316%2F80032%2F1%2F1-s2.0-S0920379613000835-main.pdf&usg=AOvVaw2ohqRaVjYKvQkLhwsh0hZR) as far as i understand.

should i include Portugal and Iran?

**Comment by ralphlange** [comment]
The Iranian Light Source will be using the Tango control system software.
(see the ["ILSF Conceptual Design Report"](http://ilsf.ipm.ac.ir/Publications/ILSF-CDR.pdf))

Portugal: yes, please.

**Comment by keijokorhonen** [comment]
The banner on the website now has the correct Chinese, Pakistani and Portugese flags.
