### ISSUE TITLE
Base-3.14.12.8 Release?

### ISSUE THREAD

**Issue by anjohnson** [epics-base/website#18]
By the time you guys read this I will have announced the final Base-3.14.12.8 release which I just tagged and uploaded to Launchpad and the APS website. If you look carefully the new site does have pages for the 3.13 and 3.14 series and for the 3.14.12 releases, but [the latter page](https://epics-controls.org/resources-and-support/base/series-3-14/3-14-12/) hasn't been updated since 3.14.12.6. Should it be brought up to date?

**Comment by ralphlange** [comment]
Yes, of course.

**Comment by ralphlange** [comment]
Page was updated by @anjohnson on 18 Sep. Closing.
