### ISSUE TITLE
Page template does not render blockquotes properly

### ISSUE THREAD

**Issue by ralphlange** [epics-base/website#19]
Similar to the lists, also blockquotes are not rendered properly. (Font, font size, spaces, ...)
See https://epics-controls.org/resources-and-support/documents/howto-documents/channel-access-reach-multiple-soft-iocs-linux/

**Comment by keijokorhonen** [comment]
I made some adjustments to this. Could you look at the page you posted again and let me know if that needs any improvements?

**Comment by ralphlange** [comment]
Almost there. For me, the font size in the blockquote is still unnaturally big compared to the normal font. See:
![image](https://user-images.githubusercontent.com/632191/60875253-be3cc500-a239-11e9-9e7f-76ff6f786d11.png)

**Comment by keijokorhonen** [comment]
What about now? I changed the font size to 14px.

**Comment by ralphlange** [comment]
No change as far as I can see.

**Comment by ttkorhonen** [comment]
This is how it looks on my (Firefox) browser. To me the font looks smaller. Also there is no scrollbar.
![blockquotes](https://user-images.githubusercontent.com/12592940/60876837-f4c80f00-a23c-11e9-98bd-9e954297793d.png)

**Comment by ralphlange** [comment]
Now it's the same for me. Good!

**Comment by ralphlange** [comment]
(Probably the server-side cache timed out...)
