### ISSUE TITLE
Error in transient (page loading) animation on project page

### ISSUE THREAD

**Issue by ralphlange** [epics-base/website#2]
Globally, the animation played when a page is loading are 3 x 3 dots changing size.

However, when the EPICS Users / Projects page loads, two animations are shown: the regular 3x3 dots and, above, a large single dot.

This might be related to the Projects page being handled by s different plug-in. It's somewhere down in the template code and I was not able to locate the bug.

**Comment by ttkorhonen** [comment]
(Keijo) Found the CSS class of the loading element buried deep in the "cherry projects" plug-in javascript code and made it invisible using WordPress' "Additional CSS" function.

**Comment by ralphlange** [comment]
You are my new CSS god. Excellent!
