### ISSUE TITLE
Banners with flags need an update: Pakistan

### ISSUE THREAD

**Issue by ralphlange** [epics-base/website#22]
As we officially have EPICS users in Pakistan now, the banners using the chain of flags might need an update at some time.
This can be combined with the second half of issue #14, maybe?

**Comment by ttkorhonen** [comment]
Dirk, can you take a look at this, when you find the time?

**Comment by epicDirk** [comment]
yes i will integrated the flag of Pakistan

**Comment by keijokorhonen** [comment]
The banner on the website now uses the flag of Pakistan.

**Comment by ralphlange** [comment]
FWIW:
The Projects and Links pages do not have a banner currently.

**Comment by ttkorhonen** [comment]
Should they? On that sub-level, none of the other pages have banners either. For example, Licensing, or none that I looked at. I personally prefer it that way.

**Comment by ralphlange** [comment]
They used to have, and Dirk made new banners for these.
It's a graphics design topic - so I have no opinion.
