### ISSUE TITLE
Where are the download files?

### ISSUE THREAD

**Issue by ralphlange** [epics-base/website#23]
I created a new page for EPICS Base 3.15.6 (following the instructions on the web site documentation).
Also added the appropriate table rows to the different tables (could be included in the web site doc).

Now I am puzzled about the download files (.tar.gz and signature). All download links to existing releases point to our epics-controls site, but I can't find the files anywhere and I don't know where to upload the files for my new release.

I would expect such content in the media library - but it's not there. The Download page also shows no clue. Please help.

**Comment by keijokorhonen** [comment]
All the download files are located on the host server and can't be accessed through the wordpress dashboard, but through e.g. ssh. Heinz should be able to help you with this further.

**Comment by ralphlange** [comment]
Ok, thanks a lot, that explains a few things.... ;-)
@hjunkes, may I get ssh access, please?!

**Comment by hjunkes** [comment]
Ok there is now also an account for ralph on that system

**Comment by ralphlange** [comment]
Thank you! Closing the issue.
