### ISSUE TITLE
RSS Feed for News and Events

### ISSUE THREAD

**Issue by ralphlange** [epics-base/website#24]
EPICS has no "Announcements" channel for people who are not interested in the tech-talk details but want to stay informed about major events.
The "News and Events" posts would have the right amount of content - we just need a way to create a "push" type of subscription. An RSS feed would be one option.

**Comment by ralphlange** [comment]
@ralphlange should inform Klaus Kneupner when this is available.

**Comment by keijokorhonen** [comment]
Wordpress has an included RSS feed for posts, which can be found at https://epics-controls.org/feed/. This would include all posts from the "Meetings and other events" and "Software Releases" columns. For only meetings we have https://epics-controls.org/category/meetings/feed/ and for releases we have https://epics-controls.org/category/releases/feed/. I can add these to the "Elsewhere" column in the bottom menu.

**Comment by ralphlange** [comment]
Perfect!

**Comment by ttkorhonen** [comment]
RSS feed link in my browser:
![RSSFeed](https://user-images.githubusercontent.com/12592940/60894586-48e5ea00-a263-11e9-8c7a-bc04f02c2eb3.png)

**Comment by anjohnson** [comment]
Will there be links to these feeds shown on the relevant pages too, with the RSS logo? I don't see the Elsewhere column as an obvious place for them, I wouldn't look there myself if I was looking for a feed. A search for "RSS" didn't find them either just now.

**Comment by keijokorhonen** [comment]
Links have been added to the News and Events page.
