### ISSUE TITLE
Update WordPress to version 5.0

### ISSUE THREAD

**Issue by ralphlange** [epics-base/website#26]
WordPress recently had a new major release, v5.0.

Currently (December 2018), 5.0 is still too new to jump on it: not even all plugins we use have been tested for compatibility with the new version.
But, at some point in 2019, we will have to tackle the task of updating and fully checking the functionality of all themes and plugins we use.

Does this smell like a summer student project? Yes, it does, @keijokorhonen.

**Comment by keijokorhonen** [comment]
The website has been upgraded to Wordpress 5.2.2 and with that we also changed the theme got rid of Power Builder and made a few other improvements. All plugins we use should still be intact. All (or at least most) Pages have been converted to use Gutenberg also. Now, if you excuse me, my fingers hurt...
