### ISSUE TITLE
Remove mailing lists QTi-talk and Hw-talk

### ISSUE THREAD

**Issue by anjohnson** [epics-base/website#29]
The two APS mailing lists QTi-talk and Hw-talk are being decommissioned, they were not being used any more, with only 1 post to each in 2018. The archives are still present on the Argonne EPICS website and will remain there, but the mailman links and email addresses will probably stop working sometime in the next few days/weeks.

I should be able to make the necessary changes to this website sometime after I get back from vacation in a week or so's time, but if someone else wants to do that first I'd be very appreciative. I already adjusted the Argonne EPICS website pages, so feel free to steal wording from there if necessary.

**Comment by keijokorhonen** [comment]
I updated the page to use the new wording and removed the subscribe and send links. Should these lists be completely removed from the page or are these small updates enough?

**Comment by anjohnson** [comment]
That looks fine now, thanks.
