### ISSUE TITLE
Switch site to https

### ISSUE THREAD

**Issue by ralphlange** [epics-base/website#3]
testsite.epics7.org only works through unsecure http and doesn't answer to https requests.
Instead, http requests should be forwarded to the appropriate https URL.

**Comment by epicAzadeh** [comment]
This is related to the web host security that is listed in the hosting requirements.
Does the new host offer a free SSL certificate, if not, we have to buy it and we have various options such as the below providers (links):
- Standard SSL/1-year Price =$175 USD( https://www.digicert.com/buy-ssl-certificates/ )
- Comodo SSL/ 1-year Price =€88.95 (https://ssl.comodo.com/avoid-not-secure-warning-in-chrome.php)

**Comment by ralphlange** [comment]
Agreed. We will need a proper (i.e. not self-signed) cert to do this.
@hjunkes you have your own CA, right?

**Comment by hjunkes** [comment]
Yes, we have a own CA but we can only create certs for .mpg.de
I would use let's encrypt (https://letsencrypt.org) to create a certificate for epics-controls.org

**Comment by ralphlange** [comment]
With the move to the new location at https://epics-controls.org/, the web site fully supports https (using a cert from 'Let's Encrypt') and http requests are redirected to use https.
