### ISSUE TITLE
Scaling on small viewports

### ISSUE THREAD

**Issue by dirk-zimoch** [epics-base/website#5]
Some pages do not scale well on small viewports, for example the main page and the "projects" page. The pictures become smaller and smaller until unrecognizable. On the "about" page it works much better.

**Comment by ttkorhonen** [comment]
This was worked on during the summer and I think most if not all issues have been resolved. If there are still problems it would be good to point them explicitly out.

**Comment by ralphlange** [comment]
@dirk-zimoch: same thing here. Please re-check and close the issue if things are working for you.

**Comment by dirk-zimoch** [comment]
Everything seems to work nice now on smaller viewports.
